### ISSUE TITLE
Adicionar no Readme como executar o projeto

### ISSUE THREAD

**Issue by rhskiki** [JoaoIto/alura_discord#1]
Está faltando no readme.md a explicação de como rodar o projeto em Next e quais os pacotes são necessários para rodar o projeto.

**Comment by JoaoIto** [comment]
Tá feito, esta colocado, só baixar o projeto e tentar executar na sua máquina! Infelizmente ainda não aprendi como posso fazer deploy da aplicação em Next.js, então por enquanto só pode ser rodado localmente, ou seja, baixado na sua máquina
